### PR TITLE
Make column/line optional in reporting

### LINKED ISSUE #162: Cannot gracefully handle lack of :line / :column from linter reports
## Brief

Macro-based code doesn't always emit a line/col mapping.

Accordingly, Eastwood reports coming from such code will lack a :line / :column, which will violate our spec:

https://github.com/nedap/formatting-stack/blob/57e4651fa0913bc4a65415c07b86c3e1dac403a2/src/formatting_stack/protocols/spec.clj#L57-L58

## Expected behavior

Linter faults lacking this info are reported like a regular one.

## Actual behavior

They are reported like exceptions instead, having a long stacktrace, Expound report etc.

## Screenshot, stacktrace, etc

```
{:namespace-sym xxxx.login,
    :linter :suspicious-expression,
    :msg
    "dissoc called with 1 args.  (dissoc map) always returns map.  Perhaps there are misplaced parentheses?",
    :uri-or-file-name
    "xxxxxxxxxxxlogin.clj",
    :source :eastwood/suspicious-expression,
    :level :warning,
    :filename
    "xxxxxxxxx.clj",
    "warning-details-url"
    "https://github.com/jonase/eastwood#suspicious-expression",
    :uri
    #object[java.net.URI 0x12110009 "file:xxxxxxxxxxlogin.clj"],
    :loc nil,
    :warning-details-url
    "https://github.com/jonase/eastwood#suspicious-expression"}
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

should contain keys: :column, :line
```

## Environment info

f-s latest

cc/ @thumbnail

### PR DESCRIPTION
**Pull request by thumbnail**
## Brief

Fixes #162

## QA plan

Run `4.2.3-alpha1` on code used to trigger #162

## Author checklist

* [ ] I have QAed the functionality
* [x] The PR has a reasonably reviewable size and a meaningful commit history
* [x] I have run the [branch formatter](https://github.com/nedap/formatting-stack/blob/332a419034ab46fad526a5592f4257353bd695b6/src/formatting_stack/branch_formatter.clj) and observed no new/significative warnings
* [x] The build passes
* [x] I have self-reviewed the PR prior to assignment
* Additionally, I have code-reviewed iteratively the PR considering the following aspects in isolation:
  * [x] Correctness
  * [x] Robustness (red paths, failure handling etc)
  * [x] Test coverage
  * [x] Spec coverage
  * [ ] Documentation
  * [ ] Security
  * [ ] Performance
  * [x] Breaking API changes
      - This change is relaxing, and thus backwards compatible.
  * [ ] Cross-compatibility (Clojure/ClojureScript)

## Reviewer checklist

* [ ] I have checked out this branch and reviewed it locally, running it
* [ ] I have QAed the functionality
* [ ] I have reviewed the PR
* Additionally, I have code-reviewed iteratively the PR considering the following aspects in isolation:
  * [ ] Correctness
  * [ ] Robustness (red paths, failure handling etc)
  * [ ] Test coverage
  * [ ] Spec coverage
  * [ ] Documentation
  * [ ] Security
  * [ ] Performance
  * [ ] Breaking API changes
  * [ ] Cross-compatibility (Clojure/ClojureScript)

### CODE REVIEW

File: src/formatting_stack/protocols/spec.clj [hunk 1]
```diff
@@ -53,10 +53,10 @@ so that final users can locate them and configure them."
   (spec/keys :req-un [::filename
                       ::source
                       ::msg
-                      ::level
-                      ::column
-                      ::line]
-             :opt-un [::msg-extra-data
+                      ::level]
+             :opt-un [::column
```
Comment (vemv) [inline src/formatting_stack/protocols/spec.clj:57]: Since we're not covering with tests that a specific macro can cause the original issue (which honestly would be pretty contrived, if not unreliable), I'd add over here a comment explaining why these keys are (now) optional.

That comment would be our "tests" ;p

Also interesting in a future to make these keys required for linters that we know that can't fail. OTOH there's a risk of hitting similar issues again

**Review by vemv — COMMENTED** [review]
Consumed the alpha, verified that now the linter report is printed flawlessly.

image

Nice `?`s! Thanks so much for this one.

**Review by jwkoelewijn — APPROVED** [review]
